# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: "Grandpa Kenny's Fishing Adventure"
description: "A 2D RPG fishing game"

short_url: 'fishwithkenny.com'
# google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
#permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /blog/:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
# safe: false
# lsi: false
# username: jekyller
# repo: jasper
# branch: master
# relative_source: ../jasper/
# destination: ../jasper-pages/
# production_url:  https://jekyller.github.io/jasper/
# source_url:  https://github.com/jekyller/jasper/

# exclude:
#   - README.md
#   - Rakefile
#   - Gemfile
#   - Gemfile.lock
#   - changelog.md
#   - "*.Rmd"
#   - vendor
#   - .travis.yml
#   - node_modules
#   - .git
